//
//  ThemeArray.swift
//  Winner'sCircleTutorial
//
//  Created by Matthew Howes Singleton on 5/27/16.
//  Copyright © 2016 Matthew Howes Singleton. All rights reserved.
//

import Foundation
import UIKit


class LocalModal: NSObject {

    var possibleThemesArray: Array = [
        
        "Abandoned",
        "Abandoned Buildings",
        "Abstracts",
        "Anger",
        "Arches",
        "Architecture",
        "Autumn",
        "Back Alleys",
        "Bad Weather",
        "Balloons",
        "Bare Feet",
        "Barns",
        "Bokeh",
        "Bugs",
        "Bikes",
        "Birds",
        "Black and White",
        "Books",
        "Bridge",
        "Broken",
        "Cats",
        "Celebrations",
        "Choice",
        "Church Windows",
        "Churches",
        "Circles",
        "City Skylines",
        "City Street",
        "Close-up",
        "Clouds",
        "Cold",
        "Colors",
        "Colours",
        "Columns",
        "Computers",
        "Contrasts",
        "Culture",
        "Curves",
        "Custom Cars",
        "Dancers",
        "Decorations",
        "Demonic",
        "Demonstrations",
        "Devilish",
        "Digital",
        "Dishes",
        "Documentary",
        "Dogs",
        "Dominating",
        "Door Knobs",
        "Doors",
        "Drawers",
        "Duplicates",
        "Easter",
        "Eggs",
        "Elation",
        "Embrace",
        "Emergency Situations",
        "Enthusiasm",
        "Environmental",
        "Events",
        "Feet",
        "Femininity",
        "Fences",
        "Festivals",
        "Fetish",
        "Fire",
        "Fireworks",
        "Fish",
        "Flags",
        "Flower Petals",
        "Flowers",
        "Food",
        "Fountains",
        "Frame",
        "Freeways",
        "Frozen",
        "Fruit",
        "Games",
        "Gardens",
        "Gates",
        "Gears",
        "Glamour",
        "Glass",
        "Graffiti",
        "Green",
        "Habits",
        "Hands",
        "Halloween",
        "Hallways",
        "Handles",
        "Hands",
        "Happiness",
        "Harbors",
        "Harvest",
        "Hats",
        "Hidden",
        "History",
        "Holiday",
        "Horizon",
        "Horses",
        "Hunger",
        "Ice",
        "Inclines",
        "Industrial",
        "Insects",
        "Inspiration",
        "Iron",
        "Isolated",
        "Jails",
        "Jets",
        "Jewelry",
        "Jobs",
        "Journalistic",
        "Joy",
        "Jugs",
        "Junk",
        "Keys",
        "Kids",
        "Kite",
        "Knives",
        "Landscapes",
        "Lazy",
        "Learning",
        "Leaves",
        "Legs",
        "Letters",
        "Light",
        "Lightning",
        "Lights",
        "Locks",
        "Macro",
        "Marine life",
        "Masculinity",
        "Masks",
        "Mirrors",
        "Money",
        "Monuments",
        "Mood",
        "Mushrooms",
        "Neon Signs",
        "Night",
        "Night lights",
        "Nighttime",
        "Nonsense",
        "Numbers",
        "Nuts",
        "Objects",
        "Odd",
        "Old",
        "Olympic",
        "Opposites",
        "Pairs",
        "Parallel Lines",
        "Patterns",
        "People",
        "People At Work",
        "People Walking Dogs",
        "Peppers",
        "Perspective",
        "Pets",
        "Piles",
        "Polished",
        "Porches",
        "Portraits",
        "Quad",
        "Quarters",
        "Queens",
        "Railroad Cars",
        "Railroad Tracks",
        "Raindrops",
        "Rainbows",
        "Red",
        "Red Barns",
        "Reflection",
        "Religious",
        "Rocks",
        "Round",
        "Rows",
        "Rust",
        "Rustic",
        "Sand dunes",
        "Sand Patterns",
        "Sea Shells",
        "Seascapes",
        "Seasons",
        "Self",
        "Shadows",
        "Shoes",
        "Signs",
        "Silhouettes",
        "Skulls",
        "Sky",
        "Sleeping",
        "Smiles",
        "Snow",
        "Soft",
        "Sorrow",
        "Speed",
        "Spoons",
        "Sports",
        "Spring",
        "Squirrel",
        "Stacks",
        "Stairs",
        "Statues",
        "Steam Railroads",
        "Still life",
        "Strange Signs",
        "String Instruments",
        "Structures",
        "Summer",
        "Sunrise",
        "Sunset",
        "Superstitions",
        "Sweets",
        "Swings",
        "Tattoos",
        "Teddy Bear",
        "Textures",
        "Toads",
        "Tombstones",
        "Tools",
        "Transport",
        "Trees",
        "Ugly",
        "Umbrella",
        "Uniforms",
        "Urban",
        "Utensils",
        "Vacation",
        "Valves",
        "Vegetables",
        "Vices",
        "Views",
        "Vignettes",
        "Vines",
        "Visitors",
        "Watches",
        "Water",
        "Waterfalls",
        "Weather",
        "Wet",
        "Wheels",
        "Wide Angle",
        "Wildlife",
        "Windows",
        "Winter",
        "Woods",
        "Xenophobia",
        "Yachts",
        ]

    
    
}